#!/bin/bash

echo "DRIFTER_NODES: $DRIFTER_NODES"
echo "DRIFTER_TARGET_REPO: $DRIFTER_TARGET_REPO"
echo "DRIFTER_TARGET_BRANCH: $DRIFTER_TARGET_BRANCH"
echo "DRIFTER_LOOP_ARGS: $DRIFTER_LOOP_ARGS"
echo "DRIFTER_LIB_BRANCH: $DRIFTER_LIB_BRANCH"
echo "DRIFTER_VERBOSE: $DRIFTER_VERBOSE"
