# -*- mode: ruby -*-
# vi: set ft=ruby :

servers=[
  {
    :hostname => "vm0",
    :name => "java8-centos7-vm0",
    :ram => 2048,
    :cpu => 1,
    :ssh_port => 2200
  },
  {
    :hostname => "vm1",
    :name => "java8-centos7-vm1",
    :ram => 2048,
    :cpu => 1,
    :ssh_port => 2201
  },
  {
    :hostname => "vm2",
    :name => "java8-centos7-vm2",
    :ram => 2048,
    :cpu => 1,
    :ssh_port => 2202
  },
  {
    :hostname => "vm3",
    :name => "java8-centos7-vm3",
    :ram => 2048,
    :cpu => 1,
    :ssh_port => 2203
  },
  {
    :hostname => "vm4",
    :name => "java8-centos7-vm4",
    :ram => 2048,
    :cpu => 2,
    :ssh_port => 2204
  },
  {
    :hostname => "vm5",
    :name => "java8-centos7-vm5",
    :ram => 2048,
    :cpu => 2,
    :ssh_port => 2205
  }
]

Vagrant.configure(2) do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = "centos/7"
            node.vm.hostname = machine[:hostname]

            node.vm.provider "virtualbox" do |vb|
              vb.gui = false
              vb.name = machine[:name]
              vb.memory = machine[:ram]
              vb.cpus = machine[:cpu]
            end
  
            if Vagrant.has_plugin?("vagrant-timezone")
              node.timezone.value = :host
            end

            node.vm.network :forwarded_port, guest: 22, host: machine[:ssh_port], id: "ssh"
            node.ssh.insert_key = false
            node.ssh.port = machine[:ssh_port]
            node.vm.box_check_update = false
            node.vm.synced_folder "~", "/vagrant_data"

            node.vm.provision "shell", inline: <<-SHELL
              cat > /etc/yum.conf <<'_EOF'
[main]
cachedir=/vagrant_data/tmp/yum/$basearch/$releasever
keepcache=1
debuglevel=2
logfile=/var/log/yum.log
exactarch=1
obsoletes=1
gpgcheck=1
plugins=1
installonly_limit=5
bugtracker_url=http://bugs.centos.org/set_project.php?project_id=23&ref=http://bugs.centos.org/bug_report_page.php?category=yum
distroverpkg=centos-release
_EOF
              yum install epel-release java-1.8.0-openjdk-devel git net-tools nload psmisc -y
              groupadd docker
              usermod -aG docker vagrant
              yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
              yum install docker-ce -y
              systemctl enable docker
              systemctl start docker
              curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
              chmod +x /usr/local/bin/docker-compose
            SHELL
        end
    end
end
