# -*- mode: ruby -*-
# vi: set ft=ruby :

servers=[
  {
    :hostname => "vm0",
    :name => "java10-centos7-vm0",
    :ram => 768,
    :cpu => 1,
    :ssh_port => 2200
  },
  {
    :hostname => "vm1",
    :name => "java10-centos7-vm1",
    :ram => 768,
    :cpu => 1,
    :ssh_port => 2201
  },
  {
    :hostname => "vm2",
    :name => "java10-centos7-vm2",
    :ram => 768,
    :cpu => 1,
    :ssh_port => 2202
  },
  {
    :hostname => "vm3",
    :name => "java10-centos7-vm3",
    :ram => 768,
    :cpu => 1,
    :ssh_port => 2203
  },
  {
    :hostname => "vm4",
    :name => "java10-centos7-vm4",
    :ram => 1024,
    :cpu => 2,
    :ssh_port => 2204
  },
  {
    :hostname => "vm5",
    :name => "java10-centos7-vm5",
    :ram => 1024,
    :cpu => 2,
    :ssh_port => 2205
  }
]

Vagrant.configure(2) do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = "centos/7"
            config.vm.box_version = ">=1804.02"
            node.vm.hostname = machine[:hostname]

            node.vm.provider "virtualbox" do |vb|
              vb.gui = false
              vb.name = machine[:name]
              vb.memory = machine[:ram]
              vb.cpus = machine[:cpu]
            end
  
            if Vagrant.has_plugin?("vagrant-timezone")
              node.timezone.value = :host
            end

            node.vm.network :forwarded_port, guest: 22, host: machine[:ssh_port], id: "ssh"
            node.ssh.insert_key = false
            node.ssh.port = machine[:ssh_port]
            node.vm.box_check_update = false
            node.vm.synced_folder "~", "/vagrant_data"

            node.vm.provision "shell", inline: <<-SHELL
              cat > /etc/yum.conf <<'_EOF'
[main]
cachedir=/vagrant_data/tmp/yum/$basearch/$releasever
keepcache=1
debuglevel=2
logfile=/var/log/yum.log
exactarch=1
obsoletes=1
gpgcheck=1
plugins=1
installonly_limit=5
bugtracker_url=http://bugs.centos.org/set_project.php?project_id=23&ref=http://bugs.centos.org/bug_report_page.php?category=yum
distroverpkg=centos-release
_EOF

              yum install epel-release git net-tools nload psmisc wget kernel-devel -y
              wget --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/10.0.2+13/19aef61b38124481863b1413dce1855f/jdk-10.0.2_linux-x64_bin.tar.gz
              mkdir -p /usr/lib/jvm
              tar zxf jdk-10.0.2_linux-x64_bin.tar.gz -C /usr/lib/jvm 
              rm *jdk*.tar.gz
              alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-10.0.2/bin/java 1
              alternatives --install /usr/bin/jar jar /usr/lib/jvm/jdk-10.0.2/bin/jar 1
              alternatives --install /usr/bin/javac javac /usr/lib/jvm/jdk-10.0.2/bin/javac 1
              alternatives --install /usr/bin/jps jps /usr/lib/jvm/jdk-10.0.2/bin/jps 1
              alternatives --set java /usr/lib/jvm/jdk-10.0.2/bin/java
              alternatives --set jar /usr/lib/jvm/jdk-10.0.2/bin/jar
              alternatives --set javac /usr/lib/jvm/jdk-10.0.2/bin/javac
              alternatives --set jps /usr/lib/jvm/jdk-10.0.2/bin/jps
              groupadd docker
              usermod -aG docker vagrant 
              yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
              yum install docker-ce -y
              systemctl enable docker
              systemctl start docker
              curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
              chmod +x /usr/local/bin/docker-compose
            SHELL
        end
    end
end
